

# This file was *autogenerated* from the file test2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3p3516098627244437 = RealNumber('3.3516098627244437')
print(_sage_const_2 **(-_sage_const_3p3516098627244437 ))

